version: "3.7"

services:
  db:
    image: mysql
    container_name: "opetimize-db"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: opetimize
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/volumes/data:/var/lib/mysql
    restart: on-failure
    networks:
      - opetimize-network

  api:
    build: ./mysql_api
    container_name: "opetimize-api"
    restart: on-failure
    volumes:
      - ./database/volumes/data2:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - opetimize-network

  web:
    container_name: "opetimize-front"
    build: web/opetimize
    ports:
      - "3001:3000"
    depends_on:
      - api
    networks:
      - opetimize-network

  mobile:
    container_name: "opetimize-mobile"
    build: ./mobile/Opetimize
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - web
    networks:
      - opetimize-network
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=172.18.9.85

networks:
  opetimize-network:
    name: opetimize-network
    driver: bridge
    external: false
