version: "3.7"

services:
  db:
    build: ./database
    container_name: "opetimize-db"
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: opetimize
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/volumes/db-data:/var/lib/mysql
    networks:
      - opetimize-network

  api:
    build: .
    container_name: "opetimize-api"
    restart: on-failure
    volumes:
      - ./database/volumes/api-data:/home/node/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - opetimize-network

  mobile:
    container_name: "opetimize-mobile"
    build: ../mobile
    depends_on:
      - api
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    networks:
      - opetimize-network
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=$MY_IP

networks:
  opetimize-network:
    name: opetimize-network
    driver: bridge
    external: false
